server {
    listen 80;
    client_max_body_size 500M;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /asr {
        proxy_pass http://whisper:9000/asr;
        proxy_read_timeout 3600;
    }

    location /asr-fast {
        proxy_pass http://whisper-fast:9000/asr;
        proxy_read_timeout 3600;
    }
}
