server {
    listen 80;
    client_max_body_size 500M;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /asr {
        proxy_pass http://whisper:9000/asr;
        proxy_read_timeout 300;
    }

    location /ocr {
        proxy_pass http://ocr:5000/ocr;
        proxy_set_header Host $host;
        proxy_read_timeout 60;
    }
}
